spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=blendb
spring.datasource.password=Park-1743***
spring.datasource.driver-class-name=org.postgresql.Driver

//spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8080

spring.main.allow-bean-definition-overriding=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# 하이버네이트가 생성하는 SQL을 정렬해서 가독성 있게 출력
spring.jpa.properties.hibernate.format_sql=true

# 쿼리 실행 시 ? 자리에 들어가는 실제 파라미터 값(들)을 로그에 출력
logging.level.org.hibernate.orm.jdbc.bind=trace

# 최하단에 이 설정을 추가하여 서버 빌드 엔진이 파일 변화를 감지하게 만듭니다.
spring.main.banner-mode=off

# 개발 단계라면 update로 되어 있어야 엔티티 변경 시 DB에 컬럼이 자동으로 추가됩니다.
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB